# load("@grpc_java//:java_grpc_library.bzl", "java_grpc_library")
# load("@protobuf//bazel:java_proto_library.bzl", "java_proto_library")
# load("@protobuf//bazel:proto_library.bzl", "proto_library")
# load("@rules_go//go:def.bzl", "go_library")
# load("@rules_go//proto:def.bzl", "go_proto_library")

package(default_visibility = ["//visibility:public"])

