load("@rules_java//java:java_binary.bzl", "java_binary")

# deps you may need for various targets
#    "@grpc_java//core",
#    "@grpc_java//netty",
#    "@junit_junit//jar" - optional

java_binary(
    name = "HelloBazelBootcamp",
    srcs = ["HelloBazelBootcamp.java"],
)
